first_pagination_locator = '//li[@class="pagination__item"]/a[contains(@class,"pagination__link pagination__link--active")]'
previous_btn_at_the_bottom_locator = '//div[@class="pagination ng-star-inserted"]/a[contains(@title,"До попередньої сторінки")]'  # '//div[@class="pagination ng-star-inserted"]/a[contains(@class,"button button--gray button")]'
next_btn_at_the_bottom_locator = '//div[@class="pagination ng-star-inserted"]/a[contains(@title,"До наступної сторінки")]'  # '//div[@class="pagination ng-star-inserted"]/a[contains(@class,"pagination__direction--forward")]'
second_paginator_locator = '//div[@class="pagination ng-star-inserted"]//a[contains(text(),"2")]'
laptop_images_per_default = '//img[contains(@class,"lazy_img_hover")]'
laptop_list_item = '//ul[@class="catalog-grid ng-star-inserted"]/li[@class="catalog-grid__cell catalog-grid__cell_type_slim ng-star-inserted"]//rz-button-product-page[@class ="ng-star-inserted"]//span[@class = "goods-tile__title"]'
checkbox_apple = '//ul[@class="checkbox-filter"]/li[@class="checkbox-filter__item ng-star-inserted"]/a[@data-id = "Apple"]'
